project:
  type: website
  output-dir: docs

website:
  site-url: "https://mathaw.cloudrimalaya.com"
  title: Mathatistics
  description: My personal blog where I share my experiences and my learning journey.
  favicon: images/mathatistics.svg
  cookie-consent: false
  navbar:
    logo: images/mathatistics.svg
    logo-alt: Mathatistics
    background: dark
    foreground: light
    right:
      - href: index.qmd
        text: Home
      - href: photography
        text: Photo Gallery
      - href: portfolio
        text: Portfolio
      - href: resume
        text: Resume
      - href: blog.qmd
        text: Blog
      - icon: rss
        href: blog.xml
    tools:
      - icon: github
        href: https://github.com/therimalaya
        aria-label: GitHub

format:
  html:
    filters:
      - lightbox
    fontsize: 1.2em
    linestretch: 1.75
    theme:
      light: [default, light.scss, styles.scss]
      dark: [default, dark.scss, styles.scss]
    toc: true
